name: Pull Request to Main

on:
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v6

      - name: Setup Node 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install
        run: npm i

      - name: Build
        run: npm run build
